# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node env
      uses: actions/setup-node@v2
      with: 
        #node-version: '10.x'
        node-version: '10.19.0'
        
        
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
        
    - name: nvn compile
      run: |-
        echo ${JAVA_HOME}
        echo "MAVEN_HOME"
        echo ${MAVEN_HOME}
        sudo apt update
        sudo apt install tree -y
        sudo apt install maven -y

        npm -v
        mvn --version
        
        echo "===============mvn help:system start================"
        mvn help:system
        echo "===============mvn help:system end================"
        echo "=============mvn install start==============="
        mvn install
        echo "=============mvn install end==============="

        npm -v
        echo "=============npm install start==============="
        npm install
        echo "=============npm install end==============="
        
        ls -al ${JAVA_HOME}/bin/java
        ls -al ${JAVA_HOME}/bin/javac
        echo "================="

        tree ${JAVA_HOME}
        export PATH="${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin:$PATH"

        java -version
        mvn --version
        mvn install
        mvn compile
        #mvn -B package --file pom.xml

